name: librealuvc - Continuous Integration

on:
  push

jobs:
  build-win:
    name: Build Windows Library
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Install Conan
        run: |
          pip install conan
          conan remote add conan-center https://conan.bintray.com

      - name: Install Dependencies
        run: |
          conan install . --install-folder build -r conan-center -s compiler='Visual Studio' -s compiler.version="15"

      - name: Build Windows Library
        run: |
          conan build . --install-folder build

      - name: Upload Windows Library
        uses: actions/upload-artifact@v2
        with:
          name: librealuvc-windows
          path: build/bin/
